# Generated by Django 3.2.2 on 2021-05-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, verbose_name='课程名称')),
                ('course_id', models.CharField(max_length=15, unique=True, verbose_name='课程代码')),
                ('duration', models.IntegerField(verbose_name='上课时间')),
                ('capacity', models.IntegerField(verbose_name='课程容量')),
            ],
        ),
    ]
