# Generated by Django 3.2.2 on 2021-05-24 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210524_1239'),
        ('course_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.CharField(default=1, max_length=20, verbose_name='开课学院'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer_uid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.teacher', verbose_name='授课教师教工号'),
            preserve_default=False,
        ),
    ]
