# Generated by Django 3.2.2 on 2021-05-24 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210524_1427'),
        ('course_management', '0002_auto_20210524_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_course_id', models.CharField(max_length=15, verbose_name='先修课程代码')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='info',
            field=models.CharField(blank=True, default='暂无课程介绍', max_length=255, verbose_name='课程介绍'),
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_joined', models.CharField(default='0', max_length=1, verbose_name='选课状态')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.course')),
                ('stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisite',
            field=models.ManyToManyField(blank=True, to='course_management.Prerequisite'),
        ),
        migrations.AddField(
            model_name='course',
            name='reg_stat',
            field=models.ManyToManyField(through='course_management.CourseRegistration', to='login.Student'),
        ),
    ]
