# Generated by Django 3.2.2 on 2021-05-25 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0003_auto_20210524_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
    ]
