# Generated by Django 3.2.2 on 2021-05-25 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210524_1427'),
        ('course_management', '0004_remove_course_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lecturer_uid',
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.teacher', verbose_name='授课教师'),
            preserve_default=False,
        ),
    ]
