# Generated by Django 3.2.2 on 2021-05-31 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210524_1427'),
        ('course_management', '0005_auto_20210525_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='课程成绩')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.course')),
                ('stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='stu_score',
            field=models.ManyToManyField(related_name='cm_course_related', through='course_management.StuScore', to='login.Student'),
        ),
    ]
