# Generated by Django 3.2.2 on 2021-06-02 14:24

import course_management.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20210602_1424'),
        ('course_management', '0006_auto_20210531_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '课程'},
        ),
        migrations.AlterModelOptions(
            name='courseregistration',
            options={'verbose_name_plural': '学生选课'},
        ),
        migrations.AlterModelOptions(
            name='stuscore',
            options={'verbose_name_plural': '学生成绩'},
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisite',
            field=models.ManyToManyField(blank=True, to='course_management.Prerequisite', verbose_name='先修课程'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.course', verbose_name='课程'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='is_joined',
            field=models.CharField(choices=[('0', '未中签'), ('1', '已中签')], default='未中签', max_length=1, verbose_name='选课状态'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='stu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.student', verbose_name='学生'),
        ),
        migrations.AlterField(
            model_name='stuscore',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.course', verbose_name='课程'),
        ),
        migrations.AlterField(
            model_name='stuscore',
            name='stu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.student', verbose_name='学生'),
        ),
        migrations.CreateModel(
            name='CourseFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('file', models.FileField(upload_to=course_management.models.course_dir_path, verbose_name='课程文件')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.course', verbose_name='课程名称')),
            ],
            options={
                'verbose_name_plural': '课件资料',
            },
        ),
    ]
