# Generated by Django 3.2.2 on 2021-05-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=10)),
                ('faculty', models.CharField(max_length=20, verbose_name='学院')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('info', models.CharField(blank=True, default='本人很懒，没有设置个人简介', help_text='一句话介绍自己，不要超过250字', max_length=255, verbose_name='个人简介')),
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='学号')),
                ('grade', models.CharField(max_length=5, verbose_name='年级')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=10)),
                ('faculty', models.CharField(max_length=20, verbose_name='学院')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('info', models.CharField(blank=True, default='本人很懒，没有设置个人简介', help_text='一句话介绍自己，不要超过250字', max_length=255, verbose_name='个人简介')),
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='教工号')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
