# Generated by Django 3.2.2 on 2021-05-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='student',
            name='uid',
            field=models.CharField(default=1, max_length=12, unique=True, verbose_name='学号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='uid',
            field=models.CharField(default=1, max_length=12, unique=True, verbose_name='教工号'),
            preserve_default=False,
        ),
    ]
