# Generated by Django 3.2.2 on 2021-05-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210524_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='info',
            field=models.CharField(default='本人很懒，没有设置个人简介', help_text='一句话介绍自己，不要超过250字', max_length=255, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='info',
            field=models.CharField(default='本人很懒，没有设置个人简介', help_text='一句话介绍自己，不要超过250字', max_length=255, verbose_name='个人简介'),
        ),
    ]
